name: taggables
version: 0.1.3
author: Alexander Adeniyin Ewetumo <trinoxf@gmail.com>
homepage: http://github.com/influx6/taggables.dart
description: a lightweigt beautiful web component approach
dependencies:
    browser: any
    dispatch: any
    hub: any
    bass: any
    streamable: any
    requestful: any
